spec:
  name: bidfetch-multi-source
  region: nyc
  services:
  - name: api
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: YOUR_GITHUB_REPO/bidfetch
    build_command: npm install
    run_command: npm start
    http_port: 3001
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
    - path: /
    envs:
    - key: NODE_ENV
      value: production
    - key: PORT
      value: "3001"
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3