# Prometheus configuration for BidFetcher monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configuration
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # BidFetcher API service
  - job_name: 'bidfetch-api'
    scrape_interval: 10s
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'
    scrape_timeout: 5s

  # Data ingestion service
  - job_name: 'bidfetch-ingestion'
    scrape_interval: 30s
    static_configs:
      - targets: ['ingestion:3001']
    metrics_path: '/metrics'

  # Processing service
  - job_name: 'bidfetch-processing'
    scrape_interval: 15s
    static_configs:
      - targets: ['processing:3002']
    metrics_path: '/metrics'

  # Analytics service
  - job_name: 'bidfetch-analytics'
    scrape_interval: 30s
    static_configs:
      - targets: ['analytics:3003']
    metrics_path: '/metrics'

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'

  # MongoDB metrics
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo:27017']
    metrics_path: '/metrics'

  # MinIO metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Custom application metrics
  - job_name: 'bidfetch-custom-metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/api/internal/metrics'
    basic_auth:
      username: 'metrics'
      password: 'secure_metrics_password'

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"